from typing import Protocol, Iterable
from dataclasses import dataclass

@dataclass(frozen=True)
class VaultPath:
    value: str

@dataclass(frozen=True)
class FileEntry:
    path: VaultPath
    is_dir: bool
    is_readonly: bool
    size: int
    mtime: float

class FileStore(Protocol):
    def exists(self, p: VaultPath) -> bool: ...
    def stat(self, p: VaultPath) -> FileEntry: ...
    def read_text(self, p: VaultPath) -> str: ...
    def write_text(self, p: VaultPath, content: str) -> None: ...
    def list_dir(self, p: VaultPath) -> list[FileEntry]: ...
    def rename(self, src: VaultPath, dst: VaultPath) -> None: ...
    def delete(self, p: VaultPath) -> None: ...
    def walk(self, root: VaultPath) -> Iterable[FileEntry]: ...
